<%@ Page Title="Browse By Genre" Language="C#" MasterPageFile="~/Areas/Customer/CustomerMaster.Master" AutoEventWireup="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<script runat="server">
protected void Page_Load(object sender, EventArgs e){ if(!IsPostBack){ LoadGenres(); var g=Request.QueryString["genre"]; if(!string.IsNullOrEmpty(g) && ddlGenres.Items.FindByValue(g)!=null){ ddlGenres.SelectedValue=g; LoadMoviesForGenre(g); } } }
void LoadGenres(){ using(var conn=new System.Data.SqlClient.SqlConnection(DatabaseHelper.ConnectionString)){ conn.Open(); if(!TableExists("genre",conn)){ ShowMsg("Genres table missing."); return; } using(var cmd=new System.Data.SqlClient.SqlCommand("SELECT GEN_code,GEN_name FROM genre ORDER BY GEN_name",conn)) using(var r=cmd.ExecuteReader()){ ddlGenres.Items.Clear(); ddlGenres.Items.Add(new System.Web.UI.WebControls.ListItem("-- Select Genre --","")); while(r.Read()) ddlGenres.Items.Add(new System.Web.UI.WebControls.ListItem(r["GEN_name"].ToString(), r["GEN_code"].ToString())); } } }
protected void ddlGenres_SelectedIndexChanged(object sender,EventArgs e){ moviesContainer.InnerHtml=""; lblMessage.Visible=false; if(string.IsNullOrEmpty(ddlGenres.SelectedValue)) return; LoadMoviesForGenre(ddlGenres.SelectedValue); }
void LoadMoviesForGenre(string genre){ using(var conn=new System.Data.SqlClient.SqlConnection(DatabaseHelper.ConnectionString)){ conn.Open(); DatabaseHelper.EnsureMovieColumns(conn); if(!TableExists("movies",conn)){ ShowMsg("Movies table missing."); return; } string sql=@"SELECT MOV_code,MOV_title,ISNULL(MOV_year,0) Year,ISNULL(MOV_duration,0) Duration,ISNULL(MOV_price,0) Price,ISNULL(MOV_description,'No description available') Description FROM movies WHERE MOV_genre=@g ORDER BY MOV_title"; using(var cmd=new System.Data.SqlClient.SqlCommand(sql,conn)){ cmd.Parameters.AddWithValue("@g",genre); using(var r=cmd.ExecuteReader()){ var sb=new System.Text.StringBuilder(); int count=0; while(r.Read()){ count++; string title=r["MOV_title"].ToString(); int year=Convert.ToInt32(r["Year"]); int dur=Convert.ToInt32(r["Duration"]); decimal price=Convert.ToDecimal(r["Price"]); string code=r["MOV_code"].ToString(); string desc=r["Description"].ToString(); if(desc.Length>180) desc=desc.Substring(0,177)+"..."; sb.AppendFormat("<div class='movie-card'><h3 class='movie-title'>{0}</h3><div class='movie-details'><strong>Year:</strong> {1}<br/><strong>Duration:</strong> {2} minutes<br/><strong>Description:</strong> {5}</div><div class='movie-price'>${3:F2}</div><a href='RentMovie.aspx?movie={4}' class='rent-button'>Rent</a></div>", title, year>0?year.ToString():"Unknown", dur>0?dur.ToString():"Unknown", price, code, desc); } moviesContainer.InnerHtml = count==0?"<div class='no-movies'>No movies found for this genre.</div>": sb.Insert(0,string.Format("<div style='text-align:center;margin-bottom:20px;color:#4ecdc4;font-size:1.2em;'>Found {0} movie(s)</div>",count)).ToString(); } } } }
bool TableExists(string t,System.Data.SqlClient.SqlConnection conn){ using(var cmd=new System.Data.SqlClient.SqlCommand("SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME=@t",conn)){ cmd.Parameters.AddWithValue("@t",t); return cmd.ExecuteScalar()!=null; } }
void ShowMsg(string m){ lblMessage.Text=m; lblMessage.Visible=true; }
</script>
<div style="max-width:700px;margin:0 auto;">
 <h2 style="color:#4ecdc4;text-align:center;">Browse By Genre</h2>
 <asp:DropDownList ID="ddlGenres" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlGenres_SelectedIndexChanged" />
 <asp:Label ID="lblMessage" runat="server" Visible="false" />
 <div id="moviesContainer" runat="server" style="margin-top:25px;"></div>
</div>
</asp:Content>